# Generated by Django 4.1 on 2022-08-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('ADMIN_USER', 'Admin_User'), ('SOLUTION_PROVIDER', 'Solution_Provider'), ('SOLUTION_SEEKER', 'Solution_Seeker')], default='SOLUTION_SEEKER', max_length=18),
        ),
    ]
